// gen_graph.mjs
// Generates src/graph.cpp (the flash graph) from farm-controller/topology.json.
//
//   node tools/gen_graph.mjs           rewrite src/graph.cpp
//   node tools/gen_graph.mjs --check   exit 1 if src/graph.cpp is out of date
//
// --topology <file> and --out <file> override the paths (test_host uses them
// to build a test graph).
//
// Node and edge order are copied exactly: the on-board dijkstra() breaks ties
// by that order, the same way the orchestrator does, so a reordered graph
// would plan different equal-cost routes and trigger false deviation alerts.
// Run it after every topology.json change and commit both files.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const arg = (name, fallback) => {
  const i = process.argv.indexOf(name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const topologyPath = arg("--topology", join(here, "../../../farm-controller/topology.json"));
const outPath = arg("--out", join(here, "../src/graph.cpp"));

// Must match types.h / graph.h.
const NODE_ID_LEN = 24;
const TAG_ID_LEN = 24;
const NO_NODE = 0xff;
const NODE_TYPES = { checkpoint: "Checkpoint", elevator: "Elevator", dock: "Dock", water: "Water" };

const fail = (msg) => {
  console.error(`gen_graph: ${msg}`);
  process.exit(1);
};

const topology = JSON.parse(readFileSync(topologyPath, "utf8"));
const { nodes, edges } = topology;
if (!Array.isArray(nodes) || !Array.isArray(edges)) fail("topology.json needs nodes and edges arrays");
if (nodes.length === 0 || nodes.length >= NO_NODE) fail(`node count ${nodes.length} must be 1..${NO_NODE - 1}`);
if (edges.length === 0) fail("topology needs at least one edge");  // C++ has no empty arrays

const index = new Map();
const tags = new Set();
nodes.forEach((n, i) => {
  if (typeof n.id !== "string" || !n.id || n.id.length >= NODE_ID_LEN)
    fail(`node ${i}: id must be a string of 1..${NODE_ID_LEN - 1} chars`);
  if (index.has(n.id)) fail(`duplicate node id "${n.id}"`);
  index.set(n.id, i);
  // The sensor task formats UIDs as "0x" + uppercase hex.
  if (typeof n.tag_id !== "string" || !/^0x[0-9A-F]+$/.test(n.tag_id) || n.tag_id.length >= TAG_ID_LEN)
    fail(`node "${n.id}": tag_id "${n.tag_id}" must be "0x" + uppercase hex, under ${TAG_ID_LEN} chars`);
  if (tags.has(n.tag_id)) fail(`duplicate tag_id "${n.tag_id}"`);
  tags.add(n.tag_id);
  for (const k of ["x", "y", "z"])
    if (!Number.isFinite(n[k])) fail(`node "${n.id}": ${k} must be a number`);
  if (!(n.type in NODE_TYPES)) fail(`node "${n.id}": unknown type "${n.type}"`);
});

const docks = nodes.filter((n) => n.type === "dock");
if (docks.length !== 1) fail(`need exactly one dock node, found ${docks.length}`);

edges.forEach((e, i) => {
  if (!index.has(e.from) || !index.has(e.to)) fail(`edge ${i}: ${e.from} -> ${e.to} uses an unknown node`);
  if (!Number.isFinite(e.cost) || e.cost < 0) fail(`edge ${i}: cost must be a number >= 0`);
  if (e.bidirectional !== undefined && typeof e.bidirectional !== "boolean")
    fail(`edge ${i}: bidirectional must be true or false`);
});

// JSON.stringify gives valid C string literals for these ASCII ids.
const str = (s) => JSON.stringify(s);
// Always a double literal: "1" -> "1.0", "1e+21" and "0.5" unchanged.
const num = (v) => (/[.e]/.test(`${v}`) ? `${v}` : `${v}.0`);

const out = `// graph.cpp
// GENERATED by tools/gen_graph.mjs from farm-controller/topology.json.
// Do not edit: change topology.json and run \`node tools/gen_graph.mjs\`.

#include "graph.h"

#include "types.h"

const char GRAPH_VERSION[] = ${str(String(topology.version ?? ""))};

const GraphNode GRAPH_NODES[] = {
${nodes
  .map((n) => `    {${str(n.id)}, ${str(n.tag_id)}, ${num(n.x)}, ${num(n.y)}, ${num(n.z)}, NodeType::${NODE_TYPES[n.type]}},`)
  .join("\n")}
};
const uint8_t GRAPH_NODE_COUNT = ${nodes.length};

const GraphEdge GRAPH_EDGES[] = {
${edges
  .map((e) => `    {${index.get(e.from)}, ${index.get(e.to)}, ${num(e.cost)}, ${e.bidirectional !== false}},  // ${e.from} - ${e.to}`)
  .join("\n")}
};
const uint16_t GRAPH_EDGE_COUNT = ${edges.length};

const NodeIndex GRAPH_DOCK = ${index.get(docks[0].id)};  // ${docks[0].id}

// A planned path visits each node at most once.
static_assert(${nodes.length} <= MAX_PATH_LEN, "topology has more nodes than MAX_PATH_LEN in types.h");
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(outPath, "utf8").replace(/\r\n/g, "\n");
  } catch {}
  if (current !== out) fail(`${outPath} is out of date with ${topologyPath}: run \`node tools/gen_graph.mjs\``);
  console.log(`graph: ${outPath} is up to date (${nodes.length} nodes, ${edges.length} edges)`);
} else {
  writeFileSync(outPath, out);
  console.log(`graph: wrote ${outPath} (${nodes.length} nodes, ${edges.length} edges)`);
}
