// check_contract.mjs
// Type-checks the firmware's JSON against the REAL interfaces in
// farm-controller/shared/src/types.ts, using the TypeScript compiler.
//
//   out/*.json       produced by host_test (robot -> Pi)
//   commands/*.json  sample RobotCommands (Pi -> robot); host_test parses
//                    the same files, so both directions are covered.
//
// If someone renames a field or adds an enum value in types.ts, this fails
// until comms_json.cpp is updated to match. Run via ./run.sh.

import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "out");
const cmdDir = join(here, "commands");

const load = (dir, prefix) =>
  readdirSync(dir)
    .filter((f) => f.startsWith(prefix) && f.endsWith(".json"))
    .sort()
    .flatMap((f) => {
      const v = JSON.parse(readFileSync(join(dir, f), "utf8"));
      return (Array.isArray(v) ? v : [v]).map((value) => ({ file: f, value }));
    });

const telemetry = load(outDir, "telemetry_");
const events = load(outDir, "event_");
const commands = load(cmdDir, "command_");

// Runtime checks TypeScript can't express.
const problems = [];
for (const { file, value } of [...telemetry, ...events]) {
  if (!(value.timestamp > 1e12 && value.timestamp < 1e13))
    problems.push(`${file}: timestamp ${value.timestamp} is not Unix milliseconds`);
}
for (const { file, value } of telemetry) {
  if (!/^0x[0-9A-F]+$/.test(value.current_node))
    problems.push(`${file}: current_node "${value.current_node}" is not a tag ID like 0x2A01`);
}

// Wire<T>: string enums arrive as their string values ("en_route"), so map
// each string-enum field to the union of its values. Numeric enums (Heading)
// already accept their numeric literals.
const ts = `// generated by check_contract.mjs - do not edit
import type { RobotTelemetry, RobotEvent, RobotCommand } from "../../../../farm-controller/shared/src/types";

type Wire<T> = T extends string ? \`\${T}\` : T;
type WireObj<T> = { [K in keyof T]: Wire<T[K]> };

const telemetry: WireObj<RobotTelemetry>[] = ${JSON.stringify(telemetry.map((t) => t.value), null, 2)};
const events: WireObj<RobotEvent>[] = ${JSON.stringify(events.map((e) => e.value), null, 2)};
const commands: WireObj<RobotCommand>[] = ${JSON.stringify(commands.map((c) => c.value), null, 2)};

export { telemetry, events, commands };
`;
const tsFile = join(outDir, "contract_check.ts");
writeFileSync(tsFile, ts);

const tscArgs = ["--noEmit", "--strict", "--target", "es2020", "--module", "esnext",
  "--moduleResolution", "bundler", "--skipLibCheck", tsFile];
let tscFailed = false;
try {
  execFileSync("npx", ["--no-install", "tsc", ...tscArgs], { stdio: "inherit", cwd: here });
} catch {
  tscFailed = true;
}

console.log(
  `contract: ${telemetry.length} telemetry, ${events.length} events, ${commands.length} commands checked against types.ts`
);
for (const p of problems) console.log("  FAIL " + p);
if (tscFailed || problems.length) {
  console.log("CONTRACT CHECK FAILED" + (tscFailed ? " (see tsc errors above, in out/contract_check.ts)" : ""));
  process.exit(1);
}
console.log("contract check passed");
